# 本地端口设置
mixed-port: 7890              # 本地浏览器/终端使用 (HTTP+SOCKS5 混合)
allow-lan: false               # 不允许外部访问
bind-address: "0.0.0.0"

# 工作模式
mode: rule
log-level: info

# 控制面板
external-controller: 0.0.0.0:9090
#secret: "123456"           # 控制面板密码设置
external-ui: ~/app/clash/clash-dashboard   # clash-dashboard路径设置
unified-delay: true
tcp-concurrent: true

# 开启udp
udp: true

#下面复制clash中的一些设置，重复的删掉即可

# 示例
# DNS 配置
#dns:
# 节点设置
#proxies:
# 节点组设置
#proxy-groups:
# 规则设置
#rules:
